### PR TITLE
Project Execution - M1

### PR DESCRIPTION
**Pull request by McDoxa**

### CODE REVIEW

**Comment by basir** [comment]
Prefect Answer. Did your error resolve?

**Comment by McDoxa** [comment]
Yea, I was able to resolve the error message.. Thank you

**Comment by basir** [comment]
Wait for project N1
Could you tell me what was your error and how you resolved it.

**Comment by McDoxa** [comment]
While trying to edit the package.json, I didn't know how the line "dependencies": {}, got deleted from the code. 
So I figured that out and retype the code and the error  disappeared  though it took me quite some time .

**Comment by basir** [comment]
Interesting.
Wait for module project

**Pull request merged**
